//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundFloor.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELUXE_BUSINESS
    {
        public int Id { get; set; }
        public string ZipCode { get; set; }
        public string PrimaryRecord { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<decimal> HouseholdsPerZipcode { get; set; }
        public Nullable<int> WhitePopulation { get; set; }
        public Nullable<int> BlackPopulation { get; set; }
        public Nullable<int> HispanicPopulation { get; set; }
        public Nullable<int> AsianPopulation { get; set; }
        public Nullable<int> HawaiianPopulation { get; set; }
        public Nullable<int> IndianPopulation { get; set; }
        public Nullable<int> OtherPopulation { get; set; }
        public Nullable<int> MalePopulation { get; set; }
        public Nullable<int> FemalePopulation { get; set; }
        public Nullable<decimal> PersonsPerHousehold { get; set; }
        public Nullable<decimal> AverageHouseValue { get; set; }
        public Nullable<decimal> IncomePerHousehold { get; set; }
        public Nullable<decimal> MedianAge { get; set; }
        public Nullable<decimal> MedianAgeMale { get; set; }
        public Nullable<decimal> MedianAgeFemale { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> Elevation { get; set; }
        public string State { get; set; }
        public string StateFullName { get; set; }
        public string CityType { get; set; }
        public string CityAliasAbbreviation { get; set; }
        public string AreaCode { get; set; }
        public string City { get; set; }
        public string CityAliasName { get; set; }
        public string CountyName { get; set; }
        public string CountyFIPS { get; set; }
        public string StateFIPS { get; set; }
        public string TimeZone { get; set; }
        public string DayLightSaving { get; set; }
        public string MSA { get; set; }
        public string PMSA { get; set; }
        public string CSA { get; set; }
        public string CBSA { get; set; }
        public string CBSA_DIV { get; set; }
        public string CBSA_Type { get; set; }
        public string CBSA_Name { get; set; }
        public string MSA_Name { get; set; }
        public string PMSA_Name { get; set; }
        public string Region { get; set; }
        public string Division { get; set; }
        public string MailingName { get; set; }
        public Nullable<int> Establishments2003 { get; set; }
        public Nullable<int> Employment2003 { get; set; }
        public Nullable<int> FirstQuarterPayroll2003 { get; set; }
        public Nullable<int> AnnualPayroll2003 { get; set; }
        public string EmploymentFlag2003 { get; set; }
        public Nullable<int> GrowthRank { get; set; }
        public Nullable<int> GrowthHousingUnits2003 { get; set; }
        public Nullable<int> GrowthHousingUnits2004 { get; set; }
        public Nullable<int> GrowthIncreaseNumber { get; set; }
        public Nullable<decimal> GrowthIncreasePercentage { get; set; }
        public Nullable<int> CBSAPop2003 { get; set; }
        public Nullable<int> CBSADivPop2003 { get; set; }
        public string C110thCongressionalDistrict { get; set; }
        public string C110thCongressionalLandArea { get; set; }
        public Nullable<int> DeliveryResidential { get; set; }
        public Nullable<int> DeliveryBusiness { get; set; }
        public Nullable<int> DeliveryTotal { get; set; }
        public string PreferredLastLineKey { get; set; }
        public string ClassificationCode { get; set; }
        public string MultiCounty { get; set; }
        public string CSAName { get; set; }
        public string CBSA_Div_Name { get; set; }
    }
}
