//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundFloor.Services.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeoLocationEntities : DbContext
    {
        public GeoLocationEntities()
            : base("name=GeoLocationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DELUXE_BUSINESS> DELUXE_BUSINESS { get; set; }
        public DbSet<MULTI_COUNTY> MULTI_COUNTY { get; set; }
        public DbSet<USCities> USCities { get; set; }
        public DbSet<USCity> USCity { get; set; }
        public DbSet<zipcode> zipcodes { get; set; }
    }
}
