//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundFloor.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zipcode
    {
        public string zipcode1 { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
    }
}
