//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundFloor.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTI_COUNTY
    {
        public int Id { get; set; }
        public string ZipCode { get; set; }
        public string StateFIPS { get; set; }
        public string State { get; set; }
        public string CountyFIPS { get; set; }
        public string County { get; set; }
    }
}
