//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundFloor.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCity
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Zipcode { get; set; }
        public string Areacode { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public string County { get; set; }
        public string Timezone { get; set; }
        public string DST { get; set; }
        public int DMA { get; set; }
        public string Type { get; set; }
        public string Continental { get; set; }
        public string Country { get; set; }
        public double LATD { get; set; }
        public double LOND { get; set; }
    }
}
